Sarahs-Minions/Project-Catwalk

- .gitignore
added a .git ignore file and review folder
> Review folder

- react-client/src/components/App.jsx
- react-client/src/components/product-overview/AddToCart.jsx
- react-client/src/components/product-overview/Overview.jsx
and randomized the product page on load in app
> Add to cart - conditional renders and add button

- react-client/src/components/product-overview/AddToCart.jsx
- react-client/src/components/product-overview/Overview.jsx
- react-client/src/components/product-overview/ProductDescription.jsx
- react-client/src/components/product-overview/ProductInformation.jsx
- react-client/src/components/product-overview/StyleSelector.jsx
and sale prices are now represented the way the business requirements doc asks for
> Finished style selector functionality, added product description/slogan

- react-client/src/components/Questions-Answers/Questions.jsx
- react-client/src/components/product-overview/ImageGallery.jsx
- react-client/src/components/product-overview/Overview.jsx
- react-client/src/components/product-overview/StyleSelector.jsx
renders the correct image and thumbnails but i still need to think about how to implement the core functionalitys and lay it all out correctly
> started working on image gallery component

- react-client/dist/index.html
- react-client/dist/overviewStyles.css
- react-client/src/components/App.jsx
- react-client/src/components/product-overview/AddToCart.jsx
- react-client/src/components/product-overview/ImageGallery.jsx
- react-client/src/components/product-overview/Overview.jsx
- react-client/src/components/product-overview/ProductDescription.jsx
- react-client/src/components/product-overview/ProductInformation.jsx
- react-client/src/components/product-overview/StyleSelector.jsx
layout is close to mock, dimensions are still off.  and we should import a font (https://fonts.google.com/ or something) & anything else we're all going to use in our css soon
> initial css for overview component

- react-client/dist/overviewStyles.css
- react-client/src/components/App.jsx
- react-client/src/components/product-overview/AddToCart.jsx
- react-client/src/components/product-overview/ImageGallery.jsx
- react-client/src/components/product-overview/ProductInformation.jsx
added conditional renders to the scrolling arrows on image gallery; tried to work on other image gallery requirements for a while (having only 7 thumbnails show at once) but it was hard so i just did css on my other components instead
> image gallery conditionals and some css

- react-client/dist/overviewStyles.css
- react-client/src/components/product-overview/AddToCart.jsx
1. selecting a new size changes qty back to 1 
2. when no size is selected, qty is disabled and says -
forgot to make a branch
> full functionality of dropdowns

- react-client/dist/overviewStyles.css
- react-client/src/components/product-overview/AddToCart.jsx
- react-client/src/components/product-overview/Overview.jsx
> adds get and post requests for the cart api to styleSelector component

- react-client/src/components/App.jsx
- react-client/src/components/related items/RelatedItemCard.jsx
- react-client/src/components/related items/relatedItemsElements.jsx
- react-client/src/components/related items/relatedItemsList.jsx
- react-client/src/components/related items/yourOutfitList.jsx
added another get request to retrieve the feature/value info of the current product and dynamically rendered each feature onto the comparison modal for the current product
> dynamically rendered current product features into comparison modal

- react-client/dist/overviewStyles.css
- react-client/src/components/product-overview/AddToCart.jsx
- react-client/src/components/product-overview/ImageGallery.jsx
- react-client/src/components/product-overview/ProductInformation.jsx
- react-client/src/components/product-overview/StyleSelector.jsx
- image gallery thumbnails no longer bugging out; shows 7 at a time in correct order as user scrolls back and forth with arrows  (test with product id 16060)
- added michaels star component to product info
- rounded edges of add to bag and fav buttons to match react-select tags better
- qty options no longer render for products with quantity of 0. i still need to find a product id that has no SKU's at all (not just SKU(s) with qty 0) to test if my 'OUT OF STOCK' message logic works, but i think it should
> minor fixes

- react-client/dist/overviewStyles.css
- react-client/src/components/App.jsx
- react-client/src/components/product-overview/ImageGallery.jsx
- react-client/src/components/product-overview/Overview.jsx
- react-client/src/components/product-overview/ProductDescription.jsx
- react-client/src/components/product-overview/ProductInformation.jsx
- got default view functioning as described in business req, but hardcoded locations of the arrows, and some images look really weird. css still needs a lot of work
- added the magnifying glass cursor effect when hovering over the main image but not any of the arrows or thumbnails
- clicking on default view image toggles an expandedView boolean, no expanded view functionality yet , i'll probably use react-modal to do the expanded view later
- added list of features at the bottom, still need to add social media icons too.
> Image gallery default view

- package-lock.json
- package.json
- react-client/dist/overviewStyles.css
- react-client/src/components/product-overview/ProductInformation.jsx
- npm install react-social-icons 
- and made the style options grid fill up from right instead of left
> Added social media buttons

- react-client/dist/index.html
- react-client/dist/overviewStyles.css
- react-client/dist/shared.css
- react-client/src/components/product-overview/ExpandedView.jsx
- react-client/src/components/product-overview/ImageGallery.jsx
- figuring out what has to be done for expanded view/ zoom in functionality, some parts work some dont
- going to rewrite expandedView compoonent as functional soon
- added roboto font to shared css and index html
> expanded gallery zoom and roboto font

- react-client/src/components/product-overview/ImageGallery.jsx
- react-client/src/components/related items/RelatedItemCard.jsx
- react-client/src/components/related items/relatedItemsList.jsx
- react-client/src/components/related items/yourOutfitList.jsx
add and delete buttons both work to edit Your Outfit section
> added functionality to add and delete buttons from Your Out section

- react-client/dist/index.html
- react-client/dist/overviewStyles.css
- react-client/src/components/App.jsx
- react-client/src/components/product-overview/AddToCart.jsx
- react-client/src/components/product-overview/Banner.jsx
- react-client/src/components/product-overview/ExpandedView.jsx
- react-client/src/components/product-overview/ImageGallery.jsx
- react-client/src/components/product-overview/Overview.jsx
- react-client/src/components/product-overview/ProductDescription.jsx
- react-client/src/components/product-overview/ProductInformation.jsx
- react-client/src/components/product-overview/StyleSelector.jsx
- squashed the expanded-view zooming bugs i could find by fiddling with prismazoom properties. LMK if you guys find more problems with it
- added a banner to the top with just a title for now. the mock shows a search bar there too, or we could put light/dark mode toggle there. doesn't scroll with the page currently, but it could if you guys wanted that
- added box shadow to img gallery and buttons 
- other minor css changes all over the place; arrow colors, spacing etc
- renamed some vars/classes and deleted some old comments
> Improving expanded view

- react-client/dist/reviewStyles.css
- react-client/src/components/Reviews/PostReviewForm.jsx
- react-client/src/components/Reviews/Ratings/Ratings.jsx
- react-client/src/components/Reviews/ReviewImageElement.jsx
- react-client/src/components/Reviews/ReviewTile.jsx
- react-client/src/components/Reviews/Reviews.jsx
- react-client/src/components/Reviews/ReviewsList.jsx
why arent my commit messages showing up
> More css vol2

- react-client/dist/reviewStyles.css
- react-client/src/components/App.jsx
- react-client/src/components/Reviews/PostReviewForm.jsx
- react-client/src/components/Reviews/Ratings/Ratings.jsx
- react-client/src/components/Reviews/ReviewTile.jsx
- react-client/src/components/Reviews/Reviews.jsx
- css changes 
- added an alert to let the user know they successfully added a new review
> And more css

- react-client/dist/index.html
- react-client/dist/relatedItems.css
- react-client/src/components/related items/RelatedItemCard.jsx
started css for related products cards; added borders, margin, edited container size and img size, moved the compare modal button, and made the star pink
> started css for related products

- package-lock.json
- package.json
- react-client/dist/overview.css
- react-client/src/components/App.jsx
- react-client/src/components/product-overview/ExpandedView_old.jsx
- react-client/src/components/product-overview/ImageGallery.jsx
-refactored image gallery to use react-magnifier instead of prismazoom but it has a different set of issues, going to work on both and see which ends up better
-added css fade in/fade out effects to a few things (thumbnails, icons arrows etc)
> image gallery work

- react-client/dist/overview.css
- react-client/src/components/App.jsx
box-shadows all the same, cursor effects etc
> minor css fixes

- react-client/dist/index.html
- react-client/dist/relatedItems.css
- react-client/dist/reviewStyles.css
- react-client/src/components/App.jsx
- react-client/src/components/related items/RelatedItemCard.jsx
- react-client/src/components/related items/relatedItemsList.jsx
- react-client/src/components/related items/yourOutfitList.jsx
> almost finished with css

- package-lock.json
- package.json
- react-client/dist/relatedItems.css
- react-client/src/components/related items/RelatedItemCard.jsx
- react-client/src/components/related items/yourOutfitList.jsx
used react-elastic-carousel package to implement carousel for both related products and your outfit; your outfit carousel doesn't show until there are more than 4 items
> implemented carousel and styling

- react-client/dist/overview.css
- react-client/src/components/App.jsx
- react-client/src/components/product-overview/AddToCart.jsx
- react-client/src/components/product-overview/ExpandedView.jsx
- react-client/src/components/product-overview/ImageGallery.jsx
- react-client/src/components/product-overview/ProductInformation.jsx
- react-client/src/components/product-overview/StyleSelector.jsx
- react-client/src/components/product-overview/ZoomedImage.jsx
- changed html arrows to font awesome icons
- bolded product title, uppercased category
- aligned stars and read reviews link
- made react-select dropdowns pink instead of default blue and gave them cursor-pointer while active
> I love css

- react-client/dist/relatedItems.css
- react-client/src/components/App.jsx
- react-client/src/components/related items/relatedItemsList.jsx
- react-client/src/components/related items/yourOutfitList.jsx
fixed 'Your Outfit' placement to be in line with the above 'Related Products' carousel. Also filtered through all of the related items id numbers in the initial get request to remove the product that doesn't have any images.
> fixed placement of outfit list to be same as related products

- package-lock.json
- package.json
- react-client/dist/index.html
- react-client/dist/overview.css
- react-client/src/components/App.jsx
- react-client/src/components/product-overview/AddToCart.jsx
- react-client/src/components/product-overview/Banner.jsx
- react-client/src/components/product-overview/ExpandedView.jsx
- react-client/src/components/product-overview/ImageGallery.jsx
- react-client/src/components/product-overview/Overview.jsx
- react-client/src/components/product-overview/ProductDescription.jsx
- react-client/src/components/product-overview/ProductInformation.jsx
- react-client/src/components/product-overview/StyleSelector.jsx
- react-client/src/components/product-overview/ZoomedImage.jsx
- tried to get animations working with a few different packages but none of them panned out
- enabled eslint and formatted files to it, but i disabled all the rules that would have required me to refactor stuff (prop type array is not allowed??? no way)
- had to uninstall react-social-icons from dev dependencies and install it as a regular dependency for eslint
- css on img gallery
> css and linting

- .babelrc
- package-lock.json
- react-client/src/components/Reviews/Reviews.test.jsx
- react-client/src/components/Reviews/ReviewsTest.jsx
- tests/Reviews.test.js
- tests/msw/handlers.js
got a basic test working that proves the review component can interact with an api and display data
> Babel experiment

- react-client/src/components/App.jsx
- react-client/src/components/related items/RelatedItemsTest.jsx
- tests/RelatedItems.test.js
- tests/msw/handlers.js
wrote one test for a get request from a mock API, the other to render onto mock component and both pass
> started testing, wrote 2 tests that pass

- react-client/dist/overview.css
- react-client/dist/shared.css
- react-client/src/components/App.jsx
- react-client/src/components/product-overview/AddToCart.jsx
- react-client/src/components/product-overview/Overview.jsx
- react-client/src/components/product-overview/StyleSelector.jsx
-fixed behavior of dropdowns: qty resets to - instead of 1 when the product or style changes, resets to 1 when the size changes
-made image modal x button same color as the nav arrows
-manually added dark mode color scheme css to dropdowns, buttons, and checkmarks
-added transition-duration 0.25s to all my text so it looks smoother when toggling light/dark mode
-moved light/dark mode switch to the banner at the top with css (it's still located in app, not in banner component)
-removed overscroll-y from entire page
> overview finishing touches

- react-client/src/components/ClickTracker.jsx
- react-client/src/components/Reviews/PostReviewForm.jsx
- react-client/src/components/Reviews/Ratings/Characteristics/CharacteristicsElement.jsx
- react-client/src/components/Reviews/Ratings/Characteristics/CharacteristicsList.jsx
- react-client/src/components/Reviews/Ratings/Ratings.jsx
- react-client/src/components/Reviews/Ratings/RatingsBreakdownElement.jsx
- react-client/src/components/Reviews/Ratings/RatingsBreakdownList.jsx
- react-client/src/components/Reviews/Ratings/Stars.jsx
- react-client/src/components/Reviews/ReviewImageElement.jsx
- react-client/src/components/Reviews/ReviewPhotos.jsx
- react-client/src/components/Reviews/ReviewTile.jsx
- react-client/src/components/Reviews/Reviews.jsx
- react-client/src/components/Reviews/ReviewsList.jsx
- react-client/src/components/Reviews/Search.jsx
added the custom attribute to all of the reviews widgets
> added the custom attribute to all of the reviews widgets

- .gitignore
- react-client/src/components/App.jsx
- react-client/src/components/ClickTracker.jsx
- react-client/src/components/related items/RelatedItemCard.jsx
- react-client/src/components/related items/relatedItemsElements.jsx
- react-client/src/components/related items/relatedItemsList.jsx
- react-client/src/components/related items/yourOutfitList.jsx
fixed star ratings to show correct rating for each individual item in Your Outfit list and also stored them into local storage so they load correctly after re-render and/or refresh
> Fixing ratings

- react-client/dist/relatedItems.css
- react-client/src/components/related items/yourOutfitList.jsx
was still able to add an item that was already in the Your Outfit list so made a function to iterate local storage to see if the product already existed and disabled adding the same product again
> Fixing add outfit

- react-client/src/components/Reviews/PostReviewForm.jsx
- react-client/src/components/Reviews/ReviewTile.jsx
- react-client/src/components/Reviews/ReviewsTest.jsx
- tests/reviews.test/reviews.test.js
- wrote a test that verifies the search functionality of the reviews component
- fixed the api calls so they arent an explicit call
> Testing search

- react-client/dist/relatedItems.css
- react-client/src/components/related items/RelatedItemCard.jsx
- react-client/src/components/related items/relatedItemsElements.jsx
- react-client/src/components/related items/relatedItemsList.jsx
- react-client/src/components/related items/yourOutfitList.jsx
> fixed CSS for titles

- react-client/src/components/App.jsx
- react-client/src/components/related items/yourOutfitList.jsx
> testing for deployment

- package-lock.json
- package.json
- react-client/src/components/App.jsx
- react-client/src/components/product-overview/AddToCart.jsx
- react-client/src/components/related items/relatedItemsElements.jsx
- tests/msw/handlers.js
- tests/overview.test/AddToCart.test.js
- tests/overview.test/TestAddToCart.jsx
5 tests passing for add to cart dropdowns/button
> More tests
